In [1]:
import pandas as pd

In [2]:
# Load your CSV or paste raw data
df = pd.read_csv("/Users/jon/Desktop/Ironhack/Unit 4 - Statistics & Probability/Project-Statistics/Databases/cleaned/df_cleaned_merged_web_data_pt.txt", parse_dates=["date_time"])

In [3]:
# Ordenar por visita y timestamp
df = df.sort_values(by=["visit_id", "date_time"]).reset_index(drop=True)

# Crear columna con la siguiente fecha dentro de cada visita
df["next_time"] = df.groupby("visit_id")["date_time"].shift(-1)

# Calcular el tiempo pasado en cada paso (en segundos)
df["time_spent"] = (df["next_time"] - df["date_time"]).dt.total_seconds()

# Eliminar pasos donde no se puede calcular el tiempo (Ãºltimo de cada visita)
df_steps_time = df.dropna(subset=["time_spent"]).copy()

#Eliminar process_step con valor "confirm"

df_steps_time_final = df_steps_time.loc[df_steps_time["process_step"] != "confirm"].copy()

In [4]:
df_steps_time_final.iloc[:30]

,client_id,visitor_id,visit_id,process_step,date_time,next_time,time_spent
2,9056452,306992881_89423906595,1000165_4190026492_760066,start,2017-06-04 01:07:29,2017-06-04 01:07:32,3.0
3,9056452,306992881_89423906595,1000165_4190026492_760066,step_1,2017-06-04 01:07:32,2017-06-04 01:07:56,24.0
4,9056452,306992881_89423906595,1000165_4190026492_760066,step_2,2017-06-04 01:07:56,2017-06-04 01:09:13,77.0
5,9056452,306992881_89423906595,1000165_4190026492_760066,step_3,2017-06-04 01:09:13,2017-06-04 01:09:50,37.0
7,7338123,612065484_94198474375,100019538_17884295066_43909,start,2017-04-09 16:20:56,2017-04-09 16:21:12,16.0
8,7338123,612065484_94198474375,100019538_17884295066_43909,step_1,2017-04-09 16:21:12,2017-04-09 16:21:21,9.0
9,7338123,612065484_94198474375,100019538_17884295066_43909,step_2,2017-04-09 16:21:21,2017-04-09 16:21:35,14.0
10,7338123,612065484_94198474375,100019538_17884295066_43909,step_1,2017-04-09 16:21:35,2017-04-09 16:21:41,6.0
11,7338123,612065484_94198474375,100019538_17884295066_43909,step_1,2017-04-09 16:21:41,2017-04-09 16:21:45,4.0
12,7338123,612065484_94198474375,100019538_17884295066_43909,start,2017-04-09 16:21:45,2017-04-09 16:21:59,14.0
13,7338123,612065484_94198474375,100019538_17884295066_43909,start,2017-04-09 16:21:59,2017-04-09 16:22:04,5.0
14,7338123,612065484_94198474375,100019538_17884295066_43909,step_1,2017-04-09 16:22:04,2017-04-09 16:22:08,4.0
15,7338123,612065484_94198474375,100019538_17884295066_43909,step_2,2017-04-09 16:22:08,2017-04-09 16:24:01,113.0
16,7338123,612065484_94198474375,100019538_17884295066_43909,step_3,2017-04-09 16:24:01,2017-04-09 16:24:58,57.0
18,2478628,754122351_18568832435,100022086_87870757897_149620,start,2017-05-23 20:44:01,2017-05-23 20:44:23,22.0
19,2478628,754122351_18568832435,100022086_87870757897_149620,step_1,2017-05-23 20:44:23,2017-05-23 20:45:08,45.0
20,2478628,754122351_18568832435,100022086_87870757897_149620,step_2,2017-05-23 20:45:08,2017-05-23 20:46:01,53.0
21,2478628,754122351_18568832435,100022086_87870757897_149620,step_3,2017-05-23 20:46:01,2017-05-23 20:47:01,60.0
24,5303781,817384618_23455993918,100034012_10293842356_627828,start,2017-06-06 14:04:44,2017-06-06 14:04:51,7.0
25,5303781,817384618_23455993918,100034012_10293842356_627828,step_1,2017-06-06 14:04:51,2017-06-06 14:06:15,84.0
26,5303781,817384618_23455993918,100034012_10293842356_627828,start,2017-06-06 14:06:15,2017-06-06 14:06:22,7.0
27,5303781,817384618_23455993918,100034012_10293842356_627828,step_1,2017-06-06 14:06:22,2017-06-06 14:06:27,5.0
28,5303781,817384618_23455993918,100034012_10293842356_627828,step_2,2017-06-06 14:06:27,2017-06-06 14:07:58,91.0
29,5303781,817384618_23455993918,100034012_10293842356_627828,step_3,2017-06-06 14:07:58,2017-06-06 14:08:29,31.0
31,5623007,700426174_33289797318,100037962_47432393712_705583,start,2017-04-14 16:41:51,2017-04-14 16:43:16,85.0
32,5623007,700426174_33289797318,100037962_47432393712_705583,start,2017-04-14 16:43:16,2017-04-14 16:43:55,39.0
33,5623007,700426174_33289797318,100037962_47432393712_705583,step_1,2017-04-14 16:43:55,2017-04-14 16:44:03,8.0
35,4823947,611052344_43146965242,100057941_88477660212_944512,start,2017-04-09 11:30:10,2017-04-09 11:30:40,30.0
36,4823947,611052344_43146965242,100057941_88477660212_944512,step_1,2017-04-09 11:30:40,2017-04-09 11:31:50,70.0
37,4823947,611052344_43146965242,100057941_88477660212_944512,step_2,2017-04-09 11:31:50,2017-04-09 11:32:54,64.0

In [5]:
# Convert to txt file

#df_steps_time_final.to_csv("/Users/jon/Desktop/Ironhack/Unit 4 - Statistics & Probability/Project-Statistics/Databases/cleaned/df_cleaned_web_data_vfinal.txt", index=False)